= Coding style

- Build HTML strings using `yattag`, return a `yattag.Doc` if the result is an escaped string. The
  following commands find problematic code:

----
# Don't build HTML strings manually where escaping can be forgotten.
git grep "'<" *.py
git grep '"<' *.py
# Ensure unescaped string can be added do a document as-is, only in case it's an escaped string.
git grep -n -w asis|grep -v getvalue
----

Exception to this rule is the HTML DOCTYPE header.

- Path handling: make relative paths absolute using util.get_abspath() and avoid `__file__`,
  `os.getcwd()` or `os.chdir()`. This has the benefit that real and test config/data (under `/` and
  `tests/`) can be separated.

Exception to this rule is the `static/` directory, which has no separate test instance.

== Checklist

Ideally CI checks everything before a commit hits master, but here are a few
things which are not part of CI:

- HTML validation: https://validator.w3.org/nu/?doc=https%3A%2F%2Fvmiklos.pythonanywhere.com%2Fosm

- CSS validation:
  http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fvmiklos.pythonanywhere.com%2Fosm%2Fstatic%2Fosm.css

- If an issue is fixed (either feature or bug), document that in `CHANGELOG.adoc`, which is less
  detailed than the git log. To list all issues closed since the last "release":

----
grep -B1000 '<<<<' CHANGELOG.adoc |grep /issues/|wc -l
----
