= Development notes

Even tough Python is an interpreted language, this project uses some generated code and build-time
created caches, so always run `make` after changing the code and before using it.

== Coding style

- Build HTML strings using `yattag`, return a `yattag.Doc` if the result is an escaped string. The
  following commands find problematic code:

----
# Don't build HTML strings manually where escaping can be forgotten.
git grep "'<" *.py
git grep '"<' *.py
# Ensure unescaped string can be added do a document as-is only in case it's an escaped string.
git grep -n -w asis|grep -v getvalue
----

Exception to this rule is the HTML DOCTYPE header.

- Path handling: make relative paths absolute using `util.get_abspath()`:

----
git grep __file__ *.py
git grep os.getcwd *.py
git grep os.chdir *.py
----

This has the benefit that real and test config/data (under `/` and `tests/`) can be separated via
the tests mocking that single function.

- Try to keep module size under 800 lines, so a random small improvement does not trigger the CI
  failure at 1000 lines:

----
for i in *.py; do lines=$(wc -l < $i); if [ $lines -gt 800 ]; then echo "$i is too large: $lines lines"; fi; done
----

- Try to make JS optional. If a link can be handled with and without JS, then generate HTML which
  goes to the no-JS version, then JS can tweak the DOM to invoke JS instead. This allows avoiding
  `<noscript>` tags.

== TS debugging

Bundled JS can be minified (for production) and also source maps can be added (for debugging). The
default output is for production, but touching a TS source file and invoking:

----
make TSDEBUG=1
----

produces output that is for debugging.

== Python debugging

To run a single test:

----
env PYTHONPATH=.:tests python3 -m unittest tests.test_areas.TestRelationGetOsmHouseNumbers.test_happy
----

== Checklist

Ideally CI checks everything before a commit hits master, but here are a few
things which are not part of CI:

- HTML validation: https://validator.w3.org/nu/?doc=https%3A%2F%2Fosm-gimmisn.vmiklos.hu%2Fosm

- CSS validation:
  http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fosm-gimmisn.vmiklos.hu%2Fosm%2Fstatic%2Fosm.min.css

- Run `piprot` from time to time and make sure Pyton dependencies are reasonably up to date.

- Run `npm outdated` from time to time and make sure JS dependencies are reasonably up to date.
