= Install instructions

== Linux (openSUSE Leap 15.1)

Install dependencies, so that you can run the tests:

----
sudo zypper install mypy
sudo zypper install python3-PyYAML
sudo zypper install python3-coverage
sudo zypper install python3-flake8
sudo zypper install python3-pylint
sudo zypper install python3-pytz
sudo zypper install python3-yamllint
pip install --user yamale
make check
----

Then you can create a local config:

----
cp data/wsgi.ini.template wsgi.ini
----

Populate the reference directory with TSV files for the house number and street list, then run:

----
make server
----

This allows accessing your local instance for development.

== Windows (10)

Install dependencies:

- Install git from <https://git-scm.com/download/win>, so you can clone the repo in the Command
  Prompt:

----
git clone <this repo URL>
----

- Install Python (3.7) from the Microsoft Store.

- Install Python dependencies:

----
cd osm-gimmisn
pip install -r requirements.txt
----

- Install `make`, you can find an executable via mingw, see
  <http://www.mingw.org/wiki/Getting_Started>.

- Build the generated code:

----
make
----

Check `version.py`, remove leftover quotes at line start/end from Windows' `echo` command.

Then you can create a local config:

----
copy data\wsgi.ini.template wsgi.ini
----

Populate the reference directory with TSV files for the house number and street list, then run:

----
python wsgi.py
----

This allows accessing your local instance for development.
