= Version descriptions

== master

- Resolves: gh#576 garbage collection: if a relation was created <1 month ago, then ignore it in
  parse_access_log.py

- Resolves: gh#578 garbage collection: exclude completed areas

- Resolves: gh#585 fix street mapping when street name contains commas

- Resolves: gh#594 stats: top cities: filter for valid cities + captial districts

- Resolves: gh#611 additional streets, opposite of missing streets are now searched for

- Resolves: gh#613 provide a robots.txt

- Resolves: gh#616 handle house numbers containing commas

- Resolves: gh#617 garbage collection: filter out search engine user agents

- Resolves: gh#688 reworked the toolbar

- Resolves: gh#689 additional streets: improved main page, showing # of additional streets there

- Resolves: gh#690 you can now filter for relations based on your current position

- Resolves: gh#754 missing housenumbers now ignores points without house numbers and
  conscriptionnumbers

- Resolves: gh#759 main page: default to hiding complete areas

- Resolves: gh#765 calls to overpass now always redirect back to the original page

- Resolves: gh#782 additional streets: handle streets with type=relation

- Resolves: gh#784 street mappings: invalid osm or reference names are now flagged on the missing
  housenumbers page

- Resolves: gh#830 additional streets: track OSM id of street names which come from house numbers

- Resolves: gh#861 additional streets now can generate an overpass query

- Resolves: gh#875 missing and additional streets now also have plain text and checklist output
  formats

- Resolves: gh#886 additional streets have a proper last update date

== 7.0

- Resolves: gh#564 wsgi: add support for locale-aware percent formatting

- Resolves: gh#563 city progress: avoid double link

- Resolves: gh#561 cron: update ref.count from reference_citycounts

- Resolves: gh#521 sync missing-housenumbers and missing-streets toolbars

- Resolves: gh#513 add overpass query for not yet audited street mappings

- Resolves: gh#490 stats: add per-city coverage page

- Resolves: gh#489 stats: add per-city monthly diff page

- The stats feature now tracks the count of house number editors over time

== 6.0

- The stats feature now has localized strings

- The stats feature now has good test coverage

- Resolves: gh#441 cron can now again update inactive relations once a month

- Resolves: gh#437 the locale install requirement is now documented

- Resolves: gh#436 ref street name is now shown after the osm street name if it differs

- Resolves: gh#381 stats now has trendlines

- Resolves: gh#426 missing housenumbers now allows updating from OSM with a single click

- Resolves: gh#383 stats, monthly total now has an extra column to show today's count

- Resolves: gh#385 `invalid` list items are now normalized by default

- Resolves: gh#388 cron's console output and log file now uses the same format

- Resolves: gh#414 the missing housenumber page's table is now sorted correctly even if house number
  ranges reduce the amount of items for some streets

- Resolves: gh#372 commercial house numbers now can have comments, visible as tooltips

== 5.0

- A new `/osm/housenumber-stats/hungary/` page featuring new and all-time house number data

- A new `cherry.py` glue layer to help running on top of CherryPy

- gh#380 the validator now catches strings which are
  not valid items in an `invalid:` string list

- gh#363 next to letter suffixes (42/a), now digit
  suffixes are also accepted (42/1). Both are still limited to a single-char suffix (2020-03-23)

== 4.0

- gh#344 next to the existing "txt" output, a new
  "chkl" output is available for missing house numbers of a relation, providing a plain text
  checklist. (2020-03-07)

- yaml files are now parsed build-time to improve performance (main page loads 7 times faster)

- complete line coverage for the cron code, which was the last uncovered module

== 3.0

- complete test coverage for the wsgi code

== 2.0

- gh#322 alias names are now supported for relations,
  so compatibility (with existing bookmarks) does not break when renaming. (2019-01-10)

- gh#291 added error handling for not valid relation
  names. (2019-12-12)

- gh#285: HTML output uses 42/A style for
  letter-suffixed house numbers, but plain text output uses 42a to help turning the output into
  `invalid` configs. (2019-12-06)

- gh#267: it is now possible to opt in for a more
  strict behavior where 42/B is not considered mapped when 42/A is already mapped. (2019-11-29)

- gh#269: noise in the reference can be now cleaned by
  filtering out house numbers explicitly, rather than filtering for valid ranges. (2019-11-15)

- gh#195: track what source range generated what house
  numbers for more compact results. (2019-11-10)

- gh#224: a way to generate the gpx of all streets
  missing house numbers. (2019-10-31)

- gh#237: make OSM IDs of existing house numbers
  clickable. (2019-10-22)

- gh#228: added time internal hint when the overpass
  query errors out due to not waiting enough. (2019-10-12)

- gh#204: added possibility to list certain
  reftelepules names when a specific refmegye is selected on the main page. (2019-10-09)

== 1.0

- Initial release

Enhancements up to 2019-10-07 were presented at <https://www.meetup.com/OpenStreetMap-Hungary/>.
