FROM fedora:41 AS builder

RUN dnf install -y \
    cargo \
    clang-devel \
    gettext \
    git \
    libicu-devel \
    llvm-devel \
    make \
    npm \
    sqlite-devel \
    openssl-devel

WORKDIR /opt

RUN git -C /opt clone https://github.com/vmiklos/osm-gimmisn

RUN make -C /opt/osm-gimmisn

FROM fedora:41

RUN dnf install -y \
    git \
    libicu

WORKDIR /opt

RUN git clone https://github.com/vmiklos/osm-gimmisn

WORKDIR /opt/osm-gimmisn

RUN mkdir -p target/release/ target/browser/

COPY --from=builder /opt/osm-gimmisn/target/release/osm-gimmisn target/release/osm-gimmisn
COPY --from=builder /opt/osm-gimmisn/target/browser/bundle.js target/browser/bundle.js
COPY --from=builder /opt/osm-gimmisn/target/browser/osm.min.css target/browser/osm.min.css

RUN target/release/osm-gimmisn cache-yamls data workdir

COPY /init.sh /

CMD ["/init.sh"]
