= Az osm-gimmisn használata

== Hiányzó házszámok naprakész listája

A https://vmiklos.pythonanywhere.com/osm[weboldalon] ötleteketsz találsz, hogy hol érdemes
házszámokat felmérni. A főoldalnak a következő oszlopai vannak:

1) Hiányzó házszám (suspicious-streets) kereső.

2) Házszámlista (street-housenumbers) egy területre, ez az OSM adatbázisból származik.

3) Utcalista (streets) egy területre, ez is az OSM adatbázisból származik.

4) A terület az OSM weboldalán, ahol jól látszik a határa.

A suspicious-streets szekciót érdemes elsőre nézni, ha ott szerepel olyan terület ami érdekel, akkor
ott találsz javaslatot arra, hogy milyen hiányzó házszámokat próbálj meg felmérni. Tegyük fel, hogy
a terület már szerepel a listában, a házszám valóban hiányzott, és most szerkesztetted fel az
OSM-re.  A weboldal nem frissül automatikusan, ehhez a következőt kell tenned:

1) Várj pár percet. Ha most szerkesztettél, akkor ha azonnal fut egy overpass lekérdezés, valószínű,
hogy még nem dolgozik a te szerkesztésed eredményével.

2) A street-housenumbers szekcióban keresd ki a területed és kattints az overpass lekérdezés
(overpass query) linkre. Ez egy kis időt vesz igénybe, addig ne töltsd újra az oldalt, a böngészőt
ne zárd be.

3) Ez után keresd ki a területet a suspicious-streets szekcióban és a linkre kattintva most már el
kell tűnjön a listából a felszerkesztett házszámod.

== Új reláció hozzáadása

Egy település, falu, Budapesti városrész az OSM adatbázisában relációként jelenik meg, így az
osm-gimmisn a kezelt területeket relációknak hívja. Új reláció hozzáadásához a következő lépések
szükségesek:

1) A https://github.com/vmiklos/osm-gimmisn[git repó] szerkesztésére készülj fel. Ez lehet egy `git
clone` parancssorból vagy https://help.github.com/en/articles/editing-files-in-your-repository[webes
szerkesztés].

2) Az https://www.openstreetmap.org[osm.org]-on keress rá a relációra, pl. `Kelenföld, Budapest`. Az
első találat lesz valószínűleg egy reláció link, pl. https://www.openstreetmap.org/relation/2700869.
Innen tudod a reláció OSM azonosítóját.

Szükséged lesz még a terület megye és település referenciájára, ezzel kapcsolatban a
https://wiki.openstreetmap.org/wiki/WikiProject_Hungary/Tal%C3%A1lkoz%C3%B3k/2019-04-29_Oktogon_sv%C3%A9dasztal_%C3%A9s_k%C3%B6rny%C3%A9ke#Hi.C3.A1nyz.C3.B3_h.C3.A1zsz.C3.A1mok[wikiben]
találsz segítséget.

3) A git repó `data/relations.yaml` file-jába vegyél fel egy új bejegyzést a következő formában:

----
kelenfold:
    osmrelation: 2700869
    refmegye: "01"
    reftelepules: "011"
----

Ahol a név alapvetően szabadon választható, pl `kelenfold` megfelel, a többi mező pedig fontos, hogy
stimmeljen az előző pontban kinyert értékekkel.

4) Ez után a módosítást https://github.com/vmiklos/osm-gimmisn/pull/new[pull request] formájában
beküldheted, jóváhagyás után be fog kerülni.

A lekérdezés minden reláció esetén megegyezik, leszámítva a reláció azonosítóját. A webes felületen
le tudod kérdezni a pontos overpass lekérdezést; ha a `relations.yaml` file-ba új sor kerül, akkor
ehhez (automatikusan) egy új lekérdezés generálódik. Ez igaz mind az utcákra, mind a házszámokra.
Ezzel neked nem kell foglalkoznod, a pull request jóváhagyásakor ez a generálás megtörténik a
https://vmiklos.pythonanywhere.com/osm[weboldalon] a következő linkeken.

Ha helyben szeretnél tesztelni, látogasd meg a következő útvonalakat ebben a sorrendben:

- /osm/streets/kelenfold/update-result
- /osm/street-housenumbers/kelenfold/update-result
- /osm/suspicious-streets/kelenfold/update-result

== Hibás riasztás hozzáadása

Ez hasonló az új reláció felvételéhez, csak a reláció nevéből származtatott szűrő file-ba kell
felvenni információt, például `housenumber-filters-magasut.yaml`. Tegyük fel, hogy Magasúton a
Magasúti köz páratlan oldalán az osm-gimmisn javasol egy 999 házszámot, és ez hibásnak bizonyul.
Lépések ennek elnémításához:

1) Menj ki a terepre és mérd fel, hogy a Magasúti köz páros és páratlan oldalon milyen
tartományokban vannak valós házszámok. Általában a sarkokon vannak utcatáblák, abból ezt fel lehet
mérni.

2) Például azt találtad, hogy a páratlan oldalon 1-9 a tartomány, a páros oldalon pedig 2-8. Most
már csak ezt az információt kell rögzíteni, és ezzel automatikusan el fog tűnni a hibás 999 jelzés.

3) Szerkesszed a `housenumber-filters-magasut.yaml` file-t. Ha még nincs ilyen, akkor a
legegyszerűbb ha egy letezőt lemásolsz, és kitörlöd az összes utcát.

4) A Magasúti közt így tudod leírni:

----
  magasuti_koz:
    ranges:
      - {start: '1', end: '9'}
      - {start: '2', end: '8'}
----

Ez program által értelmezhetően a 2) pontban leírt információt rögzíti. Ha az utca OSM-beli és
referenciabeli neve eltér, itt az OSM-beli nevet használd.

5) https://github.com/vmiklos/osm-gimmisn/pull/new[pull request] formájában visszaküldheted az
információt, és akkor a webes felület is ennek megfelelően frissül.

Más szavakkal, alapból nincs szűrés a potenciálisan hiányzó házszámokon, a hibás javaslatot úgy
lehet kiszűrni, hogy lefedjük a valós tartományokat, és ami ebbe nem tartozik bele, az kiszűrésre
kerül.
